# Configuração de AMBIENTE da api

nfe.ambiente=${AMBIENTE:test}

# S3 AWS
quarkus.s3.aws.credentials.type=static
quarkus.s3.aws.credentials.static-provider.access-key-id=test
quarkus.s3.aws.credentials.static-provider.secret-access-key=test

# S3 Bucket
quarkus.s3.devservices.buckets=nfe-processing-bucket
quarkus.s3.path-style-access=true
quarkus.s3.endpoint-override=http://localhost:4566
quarkus.s3.aws.region=sa-east-1
bucket.name=s3-nfe-bucket

## BDD
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:user}
quarkus.datasource.password=${DB_PASSWORD:1234}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/nfe-processing}
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.devservices.enabled=false

# Configurações do EMITENTE da NF-e
nfe.emitente.cnpj=12345678000195
nfe.emitente.razao-social=EMPRESA GRANDE LTDA
nfe.emitente.ie=0987654321
nfe.emitente.crt=3

# Endereço do Emitente
nfe.emitente.logradouro=AV SANTO ANTONIO
nfe.emitente.numero=0
nfe.emitente.complemento=QD 17 LT 01-02-03
nfe.emitente.bairro=PQ STO ANTONIO
nfe.emitente.codigo-municipio=5219756
nfe.emitente.municipio=SANTO ANTONIO DO DESCOBERTO
nfe.emitente.cep=72900000
nfe.emitente.fone=6233215175


# Configurações do CERTIFICADO DIGITAL da empresa (obrigatório para homolog e prod) (Não testado)
# Lidas via System.getenv() no NfeConfigurator — configure no ambiente do SO:
# export NFE_CERT_PATH=/caminho/para/certificado.pfx
# export NFE_CERT_PASSWORD=senha_do_certificado



# Configurações de EMAIL SMTP remetente
quarkus.mailer.from=noreply@empresagrande.com.br
quarkus.mailer.host=smtp.gmail.com
quarkus.mailer.port=587
quarkus.mailer.start-tls=REQUIRED

# Necessário Variáveis de ambiente para envio de email
# Configuráveis no terminal (não substituir aqui)

# Username (email)
quarkus.mailer.username=${SMTP_USERNAME:seu@email.com}
# SENHA DE APLICATIVO (especificamente do app, não senha real)
quarkus.mailer.password=${SMTP_PASSWORD:4321}

# Para desenvolvimento (não envia email real, só loga no console)
quarkus.mailer.mock=true


# Configuração de IMPOSTOS
# Impostos variam conforme produto e estado envolvidos na NFe.
# Ex:. Eletrônicos - Revenda com tributação normal
nfe.icms.cst=00
nfe.icms.origem=0
nfe.icms.aliquota=19.00
nfe.pis.cst=01
nfe.pis.aliquota=1.65
nfe.cofins.cst=01
nfe.cofins.aliquota=7.60
nfe.ipi.cenq=999
nfe.ipi.cst=53
